"""Generates short, casual follow-up replies.

When a real Reddit user replies to one of our posted comments, this module
writes a low-key conversational response — *no product mentions*, no pitch,
no calls to action. The goal is "talking back like a normal commenter," not
"converting a lead."
"""

from __future__ import annotations

import logging
import re

from src.app.llm import HeuristicLLMClient, LLMClient, LLMMessage, get_llm_client
from src.domain.policies import BANNED_HYPE_PHRASES
from src.learn.voice_sampler import VoiceSampler

logger = logging.getLogger(__name__)

MAX_FOLLOWUP_WORDS = 30
MAX_FOLLOWUP_SENTENCES = 2
MIN_FOLLOWUP_WORDS = 4

# Hostility / toxicity heuristic — caught early so we don't spend an LLM call
# on obvious cases. The LLM judge handles the rest.
TOXIC_KEYWORDS = (
    "fuck off",
    "fuck you",
    "shut up",
    "kill yourself",
    "kys",
    "die in",
    "go die",
    "you're a bot",
    "youre a bot",
    "this is a bot",
    "sounds like a bot",
    "reads like a bot",
    "you are a bot",
    "obvious bot",
    "clearly a bot",
    "definitely a bot",
    "written by ai",
    "generated by ai",
    "ai generated",
    "ai-generated",
    "reads like ai",
    "sounds like ai",
    "written by chatgpt",
    "this is chatgpt",
    "chatgpt wrote",
    "llm wrote",
    "text reads like ai",
    "spam",
    "spammer",
    "scam",
    "scammer",
    "report you",
    "reported",
    "downvoted",
    "trash post",
    "garbage",
    "stfu",
    "idiot",
    "moron",
    "retard",
)

LOW_VALUE_PATTERNS = (
    re.compile(r"^(thanks|thank you|ty|thx|cheers|cool|nice|ok|okay|yep|yes|no|lol|lmao|haha+|👍|🙏|✅|👌)[\s.!]*$", re.IGNORECASE),
    re.compile(r"^.{0,3}$"),  # Anything under 4 chars
)


def looks_low_value(reply_body: str) -> bool:
    text = (reply_body or "").strip()
    if not text:
        return True
    for pattern in LOW_VALUE_PATTERNS:
        if pattern.match(text):
            return True
    return False


def looks_toxic_heuristic(reply_body: str) -> bool:
    lower = (reply_body or "").lower()
    return any(keyword in lower for keyword in TOXIC_KEYWORDS)


class ConversationWriter:
    def __init__(self, llm_client: LLMClient | None = None, voice_sampler: VoiceSampler | None = None):
        self.llm_client = llm_client or get_llm_client()
        self.voice_sampler = voice_sampler or VoiceSampler()

    def is_toxic(self, reply_body: str) -> bool:
        """Returns True if the reply is hostile, abusive, or accuses us of being a bot.

        Uses the heuristic blacklist first (free), then a tiny LLM check (cheap).
        Failsafe: if the LLM call errors, we treat the reply as toxic and skip
        — better to drop a borderline case than to engage a hostile one.
        """
        if looks_toxic_heuristic(reply_body):
            return True
        if isinstance(self.llm_client, HeuristicLLMClient):
            return False
        try:
            verdict = self.llm_client.complete(
                [
                    LLMMessage(
                        role="system",
                        content=(
                            "You judge whether a Reddit reply is hostile, insulting, or accusatory. "
                            "Reply ONLY with 'yes' or 'no'."
                        ),
                    ),
                    LLMMessage(
                        role="user",
                        content=(
                            "Is this reply hostile, abusive, accusatory (calling someone a bot/scammer/spammer), "
                            "or otherwise something a calm person would not engage with? Reply 'yes' or 'no'.\n\n"
                            f"Reply text: {reply_body.strip()[:600]}"
                        ),
                    ),
                ]
            )
        except Exception as exc:
            logger.warning("Toxicity LLM check failed; treating as toxic. err=%s", exc)
            return True
        return verdict.strip().lower().startswith("y")

    def compose(
        self,
        *,
        original_post_title: str,
        our_previous_comment: str,
        reply_body: str,
        reply_author: str,
    ) -> str | None:
        """Produces a short conversational follow-up. Returns None if no good reply."""
        if looks_low_value(reply_body):
            return None
        if isinstance(self.llm_client, HeuristicLLMClient):
            return self._heuristic_reply(reply_body)
        prompt = self._build_prompt(
            original_post_title=original_post_title,
            our_previous_comment=our_previous_comment,
            reply_body=reply_body,
            reply_author=reply_author,
        )
        # Try a few times: the LLM is non-deterministic and sometimes produces
        # output that fails our _is_usable checks (e.g. too long, hype phrases,
        # ban-listed CTAs). With a ~60% per-call pass rate, 3 tries gets us to
        # ~94% effective per-cycle success rate.
        last_normalized = None
        for attempt in range(3):
            try:
                candidate = self.llm_client.complete(prompt)
            except Exception as exc:
                logger.warning("Conversation LLM failed (attempt %d); skipping. err=%s", attempt + 1, exc)
                return None
            normalized = self._normalize(candidate)
            # If the model explicitly chose to skip, respect that — don't retry.
            if normalized.upper() == "SKIP":
                return None
            if self._is_usable(normalized):
                return normalized
            last_normalized = normalized
        logger.info(
            "Conversation LLM produced %d unusable candidates; last was %r",
            3,
            (last_normalized or "")[:120],
        )
        return None

    def _build_prompt(self, *, original_post_title, our_previous_comment, reply_body, reply_author):
        instructions = "\n".join(
            [
                "You are continuing a Reddit conversation as the same author who posted the previous comment.",
                "Write a short, casual follow-up reply.",
                "",
                "Constraints:",
                "- Aim for 5-25 words. Hard cap: 30 words. Minimum: 4 words.",
                "- Sound like a relaxed redditor, not a marketer or assistant.",
                "- It's OK to drop articles, write fragments, end without a period, or comma-splice. Don't force formal transitions between sentences.",
                "- Lowercase casual fine. 'tho', 'kinda', 'tbh', 'fwiw', 'ngl', 'idk', 'imo', 'ymmv' are fine in moderation.",
                "- NEVER write three sentences that each build on the last — that escalating structure is the clearest AI tell. One thought, maybe two, done.",
                "",
                *self._voice_examples_lines(),
                "",
                "- No product mentions. No links. No 'check out' or 'you should try'.",
                "- No hype words like 'amazing', 'great', 'awesome', 'love'.",
                "- Don't restate what they said. Add one tiny new thought — a take, a small observation, a useful caveat, or a relevant tip.",
                "- Avoid ending with a question by default. Most follow-ups should end with your take or observation. Only ask a question maybe 1 in 4 times, and only if it's genuinely the most natural reply.",
                "- VARY your phrasing. Do not reuse stock phrases like 'sounds like', 'cool to hear', 'real-time sync', 'sounds promising', 'evolving nicely'. Find a fresh way to say it.",
                "- Avoid stock openers entirely. Start with the actual idea, not a reaction word.",
                "",
                "HUMAN VOICE — STRICT RULES (patterns that get called out as bot):",
                "- NEVER use em dashes (—) or en dashes. Use commas or periods.",
                "- NEVER use smart quotes. Plain ASCII only.",
                "- NEVER use exclamation marks.",
                "- NEVER start with: 'It sounds like', 'It's great', 'It's exciting', 'It's crucial', 'Such details', 'Keep up', 'I appreciate', 'Indeed,', 'Ultimately,', 'Absolutely,', 'Certainly,', 'Of course,'.",
                "- NEVER use these words — they are the clearest AI tells on Reddit:",
                "  leverage, utilize, streamline, holistic, synergy, pivotal, paramount, empower, foster, resonate,",
                "  transformative, groundbreaking, revolutionary, cutting-edge, innovative, ecosystem, scalable,",
                "  undeniably, noteworthy, wonderful, fascinating, valuable insights, navigate the, seamless,",
                "  delve into, dive deep, consider implementing, rigorous, furthermore, moreover, nonetheless,",
                "  it's worth noting, needless to say, in essence, at the end of the day, feel free to,",
                "  let me know if, i hope this helps, happy to help, great question, absolutely, certainly,",
                "  meaningful connections, meaningful results, recognizing your value, broadcasting your,",
                "  contributing to conversations, engaging with users, once people start, especially if you're.",
                "- MATCH THE FORMAT OF THE REPLY. If they said one line, reply in one line. Don't turn a short message into a three-sentence breakdown.",
                "- NEVER write 'consider [doing X]'. That is documentation language. Say what you actually know, not what someone should consider.",
                "- NEVER end with a motivational closer like 'every bit helps', 'goes a long way', 'makes a difference'. Real people don't wrap up replies with encouragement.",
                "- DO NOT cheerlead, validate, or compliment. Real users have takes, push back, qualify, or say something concrete.",
                "- Lowercase casual fragments are fine. Don't be a TA grading homework.",
                "- Don't apologize. Don't over-thank.",
                "- Do not use bullet points or lists.",
                "- If their reply is just acknowledgment ('makes sense', 'fair', 'cool'), don't reply at all — return the literal string SKIP.",
                "",
                "Context:",
                f"Original Reddit post title: {original_post_title}",
                f"Your previous comment in the thread: {our_previous_comment}",
                f"Their reply (by /u/{reply_author}): {reply_body}",
                "",
                "Output: just the reply text, no quotes, no preamble. Or the literal string SKIP if no good reply.",
            ]
        )
        return [
            LLMMessage(role="system", content="You write short, casual Reddit follow-up replies that sound like a real person, not an AI assistant."),
            LLMMessage(role="user", content=instructions),
        ]

    def _voice_examples_lines(self) -> list[str]:
        """Return prompt lines with real scraped Reddit comments as voice examples.

        Falls back to hardcoded examples if the cache is empty (first run).
        """
        real = self.voice_sampler.sample(n=5)
        if real:
            lines = ["EXAMPLES of how real people actually write short Reddit replies (these are real scraped comments):"]
            for ex in real:
                lines.append(f"  - '{ex}'")
            lines.append("")
        else:
            lines = [
                "EXAMPLES of real-redditor follow-ups (study the brevity and voice):",
                "  - 'yeah that's been my experience too. mostly the timing thing'",
                "  - 'fair, depends on scale tho'",
                "  - 'agreed. the bigger headache is the retry logic imo'",
                "  - 'huh, hadn't thought of it that way. makes sense'",
                "  - 'nah, that's a totally different setup. you're thinking of X'",
                "  - 'good point. fwiw same thing happened to me with Y'",
                "",
            ]
        return lines

    def _normalize(self, text: str) -> str:
        cleaned = " ".join((text or "").split()).strip()
        # Strip surrounding quotes if the model added them
        if (cleaned.startswith('"') and cleaned.endswith('"')) or (cleaned.startswith("'") and cleaned.endswith("'")):
            cleaned = cleaned[1:-1].strip()
        # Strip AI-tell typography: em dashes, smart quotes, exclamation marks.
        for find, repl in {"—": ", ", "–": ", ", "‘": "'", "’": "'", "“": '"', "”": '"', "…": "...", "!": "."}.items():
            cleaned = cleaned.replace(find, repl)
        cleaned = cleaned.replace(", ,", ",").replace(",,", ",")
        while ".." in cleaned and "..." not in cleaned:
            cleaned = cleaned.replace("..", ".")
        cleaned = " ".join(cleaned.split())
        return cleaned

    def _is_usable(self, text: str) -> bool:
        if not text:
            return False
        if text.upper() == "SKIP":
            return False
        words = text.split()
        if len(words) < MIN_FOLLOWUP_WORDS or len(words) > MAX_FOLLOWUP_WORDS:
            return False
        if self._sentence_count(text) > MAX_FOLLOWUP_SENTENCES:
            return False
        lower = text.lower()
        if "http" in lower or "www." in lower:
            return False
        if "prompthunt" in lower:
            return False
        if any(phrase in lower for phrase in BANNED_HYPE_PHRASES):
            return False
        if any(phrase in lower for phrase in ("check out", "you should try", "feel free to", "let me know if")):
            return False
        # Reject AI-cheerleader patterns that get flagged as bot.
        ai_tells = (
            "it sounds like", "it's great to", "it's exciting", "it's fascinating",
            "it's crucial", "valuable insights", "keep up the", "appreciate you sharing",
            "indeed", "undeniably", "noteworthy", "wonderful", "delve into",
            "dive deep", "dive into", "navigate the", "consider implementing",
            "ultimately,", "in summary", "in conclusion", "feel free to",
            "let me know if", "i hope this helps", "happy to help",
            "absolutely,", "certainly,", "of course,", "great question",
            "leverage", "utilize", "streamline", "holistic", "synergy",
            "pivotal", "paramount", "empower", "foster", "resonate",
            "transformative", "groundbreaking", "revolutionary", "cutting-edge",
            "furthermore", "moreover", "nonetheless", "it's worth noting",
            "needless to say", "in essence", "essentially,", "at the end of the day",
            # Phrases that got us called a bot in the wild
            "keeping it authentic", "staying true to your voice", "natural flow",
            "connect better with your audience", "overly polished", "ai vibe",
            "keeping it real", "your authentic", "authentic voice",
            "staying authentic", "genuine connection", "genuine voice",
            "that sounds like an interesting", "sounds like an interesting approach",
            "invaluable", "in meaningful ways", "shape product development",
            "usability insights", "overall direction", "refining features",
            "establish initial", "product development in",
            "is real",
            # The Twitter comment giveaways and similar lecture-style phrases
            "meaningful connections", "meaningful results", "recognizing your value",
            "broadcasting your", "contributing to conversations", "engaging with users",
            "once people start recognizing", "starting from scratch",
            "instead of just broadcasting", "once people start",
            "focus on engaging", "slow at first, but",
            # "consider [doing X]" — tutorial language
            "consider using", "consider adding", "consider switching",
            "consider implementing", "consider leveraging", "consider trying",
            "consider checking", "consider looking",
            # Motivational closers
            "every bit of", "every little bit", "small changes add up",
            "goes a long way", "makes a real difference", "can make a difference",
            "make all the difference", "makes all the difference",
            "in the long run", "worth the effort",
            # "to help" as sentence-ender
            "techniques to help", "tools to help", "methods to help",
            # Corporate scaling language
            "as you scale", "scale up your", "scaling up",
            # Essay / abstract-wisdom patterns
            "transitioning from", "the reality of", "it's a reminder", "matters just as much",
            "beneath the surface", "in real-world", "doesn't guarantee", "underscores",
            "highlights the importance", "at its core", "is a testament",
        )
        if any(tell in lower for tell in ai_tells):
            return False
        # No semicolons (essay style)
        if ";" in text:
            return False
        return True

    def _sentence_count(self, text: str) -> int:
        stripped = text.strip()
        if not stripped:
            return 0
        return len(re.findall(r"[.!?]+(?:\s|$)", stripped)) or 1

    def _heuristic_reply(self, reply_body: str) -> str | None:
        body_lower = (reply_body or "").lower()
        if "?" in reply_body:
            return "yeah depends on the setup honestly. what part are you trying to nail down first?"
        if any(word in body_lower for word in ("but", "however", "disagree", "actually")):
            return "fair point, that's the part i go back and forth on too."
        return None
